# Generated by Django 5.2.13 on 2026-04-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maquinas", "0001_initial"),
        ("salas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sala",
            name="maquinas",
            field=models.ManyToManyField(blank=True, to="maquinas.maquina"),
        ),
    ]
