# Generated by Django 5.2.13 on 2026-04-07 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("salas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commando",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("comando_linux", models.TextField()),
                ("comando_windows", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Execucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "iniciado_por",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "comando",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="execucoes.commando",
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="salas.sala"
                    ),
                ),
            ],
        ),
    ]
