# Generated by Django 5.2.13 on 2026-04-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("execucoes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Commando",
            new_name="Comando",
        ),
    ]
