# Generated by Django 5.2.13 on 2026-04-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execucoes", "0002_rename_commando_comando"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comando",
            name="comando_linux",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comando",
            name="comando_windows",
            field=models.TextField(blank=True, null=True),
        ),
    ]
