# Generated by Django 6.0.6 on 2026-06-27 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes', '0003_alter_comando_comando_linux_and_more'),
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('output', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='execucoes.execucao')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.maquina')),
            ],
        ),
    ]
