# Generated by Django 6.0.4 on 2026-06-30 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes', '0004_resultadomaquina'),
        ('salas', '0002_alter_sala_maquinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='concluidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='execucao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('falha', 'Falha')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='execucao',
            name='total_maquinas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='execucao',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salas.sala'),
        ),
    ]
