# Generated by Django 6.0.4 on 2026-06-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes', '0005_execucao_concluidas_execucao_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadomaquina',
            name='progresso',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('verificando_rede', 'Verificando rede'), ('aguardando_wol', 'Aguardando WoL'), ('conectando_ssh', 'Conectando SSH'), ('executando', 'Executando comando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20),
        ),
    ]
