# Generated by Django 6.0.4 on 2026-07-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes', '0006_resultadomaquina_progresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadomaquina',
            name='os_detectado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
