# Generated by Django 6.0.4 on 2026-07-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes', '0007_resultadomaquina_os_detectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
