# Generated by Django 6.0.7 on 2026-08-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes', '0008_execucao_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='comando_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucao',
            name='os_alvo',
            field=models.CharField(blank=True, choices=[('debian', 'Linux'), ('windows', 'Windows')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='execucao',
            name='comando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='execucoes.comando'),
        ),
    ]
