# Generated by Django 6.0.7 on 2026-08-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucoes', '0009_execucao_comando_texto_execucao_os_alvo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='execucao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('falha', 'Falha'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
