# Generated by Django 5.2.13 on 2026-04-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maquina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("patrimonio", models.CharField(blank=True, max_length=100, null=True)),
                ("mac_address", models.CharField(max_length=17, unique=True)),
                (
                    "tipo_os",
                    models.CharField(
                        choices=[
                            ("debian", "Debian"),
                            ("windows", "Windows"),
                            ("dual", "Dual Boot"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "os_preferido",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("ultimo_ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
