# Generated by Django 6.1.1 on 2026-10-06 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='porta_ssh',
            field=models.PositiveSmallIntegerField(default=22, help_text='Porta usada na conexão SSH e na verificação de disponibilidade.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Porta SSH'),
        ),
    ]
